document.getElementById('yourform').submit();
function jumpnama() {window.open("/");}
function link() {location.replace("/");}
function linkqq101() {location.replace("https://qq101uok.com/");}
function linkqqkopidarat() {location.replace("https://qqkopidarat1a.com/");}
function linkarenacuan99() {location.replace("https://arenacuan99tp.com/");}
function linkqqmybet() {location.replace("https://qqmybet77p.com/");}
function linkqqtopan() {location.replace("https://qqtopan8.com/");}
function link88idr() {location.replace("https://websurscene.com/");}
function link1001win() {location.replace("https://1001winobat.com/");}
function linkqqangpao() {location.replace("https://qqangpaocuan.com/Member/StreamlinedRegister?R=38B9DA8D");}
function linkqq888bet() {location.replace("https://qq888bet1bo.com/");}
function linkqqbonus() {location.replace("https://qqbonustent.com/");}
function linkqq188() {location.replace("https://qq188best.com/Member/StreamlinedRegister?R=615BDCFD");}
function linkqq724() {location.replace("https://qq724zfp.com/");}
function linkqq288() {location.replace("https://qq288im3.com/");}
function linkqq828() {location.replace("https://qq828f6j.com/Member/StreamlinedRegister?R=00147BFB");}
function linkqq801() {location.replace("https://syntactic-surprise-calculator.com/Member/StreamlinedRegister?R=513A3A0C");}
function linkqq808() {location.replace("https://schneiderpipeorgans.com/Member/StreamlinedRegister?R=BAB2F2FE");}
function linkqq882() {location.replace("https://qq882ebg.com/");}
function linkqqberak() {location.replace("https://qqberak45t.com/Member/StreamlinedRegister?R=E038C132");}
function linkqq88pro() {location.replace("hhttps://qq88pro9df.com/Member/StreamlinedRegister?R=DB3B7621");}
function linkqq303() {location.replace("https://qq303vr5.com/Member/StreamlinedRegister?R=5FC84B59");}
function jumpqq303() {location.replace("https://qq303vr5.com/Member/StreamlinedRegister?R=5FC84B59");}
function linkqqfortuna() {location.replace("https://qqfortuna3bc.com/Member/StreamlinedRegister?R=0553AB00");}
function jumpqqfortuna() {location.replace("https://qqfortuna3bc.com/Member/StreamlinedRegister?R=0553AB00");}
function linkqqbetwin() {location.replace("https://qqbetwin69q.com/Member/StreamlinedRegister?R=C7186357");}
function linkqqfunbet() {location.replace("https://qqfunbet12p.com/");}
function jumpqqfunbet() {location.replace("https://qqfunbet12p.com/");}
function linkqqvegas() {location.replace("https://qqvegas2bt.com/Member/StreamlinedRegister?R=D1DF09BC");}
function jumpqqvegas() {location.replace("https://qqvegas2bt.com/Member/StreamlinedRegister?R=D1DF09BC");}
function linkqqkingbet() {location.replace("https://qqkingbet1o1.com/Member/StreamlinedRegister?R=5457CEDC");}
function linkqqextra() {location.replace("https://qqextra11q.com/Member/StreamlinedRegister?R=5E325C1E");}
function linkqqterang() {location.replace("https://qqbieu321.com/");}
function linkqq7887() {location.replace("https://qq7887mjy.com/Member/StreamlinedRegister?R=1DD04C85");}
function linkqqfunwin() {location.replace("https://qqfunwin6w1.com/");}
function linkqqmegah() {location.replace("https://qqmegah4tz.com/Member/StreamlinedRegister?R=332B76D1");}
function linkqqfun77() {location.replace("https://qqfun77pg1.com/Member/StreamlinedRegister?R=39ED3D08");}
function linkqq999bet() {location.replace("https://qq999bet6tp.com/");}
function linkqq7997() {location.replace("https://qq7997ek8.com/Member/StreamlinedRegister?R=4668EFEF");}
function linkqqbos99() {location.replace("https://www.senisastra.com/");}
function jumpqqbos99() {location.replace("https://www.senisastra.com/");}
function linkqq8889() {location.replace("https://qq8889vgv.com/");}
function linkqq1x2() {location.replace("https://qq1x2rsu.com/");}
function linkqqkuda() {location.replace("https://cutt.ly/Daftar-QQKuda");}
function linkqqmilan() {location.replace("https://bit.ly/M1l4N");}
function linkqq2889() {location.replace("https://cutt.ly/qq2889");}
function linkqqdewa() {location.replace("https://cepat.io/qqdewalogin1");}
function linkqqemas() {location.replace("https://rdrect.cc/qqemas/");}
function linkqqnusa() {location.replace("https://secure.livechatinc.com/customer/action/open_chat?license_id=12597978&group=0");}
function linkqqmacan() {location.replace("https://linkqqmacan.com/");}
function linkluxury777() {location.replace("https://linkluxury777.com/");}
function linkqq1221() {location.replace("https://qq1221loop.org/Member/StreamlinedRegister?R=301B242B");}
function linknama() {location.replace("https://www.senisastra.com/");}
